// Be sure to keep this in sync with cursor.rs!
export const cursorMap = [
  "none", // Hidden=>0
  "default", // Default=>1,
  "crosshair", // CrossHair=>2,
  "pointer", // Hand=>3,
  "default", // Arrow=>4,
  "move", // Move=>5,
  "text", // Text=>6,
  "wait", // Wait=>7,
  "help", // Help=>8,
  "not-allowed", // NotAllowed=>9,
  "n-resize", //  NResize=>10,
  "ne-resize", //  NeResize=>11,
  "e-resize", //  EResize=>12,
  "se-resize", //  SeResize=>13,
  "s-resize", //  SResize=>14,
  "sw-resize", //  SwResize=>15,
  "w-resize", //  WResize=>16,
  "nw-resize", //  NwResize=>17,
  "ns-resize", // NsResize=>18,
  "nesw-resize", // NeswResize=>19,
  "ew-resize", // EwResize=>20,
  "nwse-resize", // NwseResize=>21,
  "col-resize", // ColResize=>22,
  "row-resize", // RowResize=>23,
];
