name: CI
on: [push]
jobs:
  build_web_ci:
    runs-on: ubuntu-latest
    container:
      image: janpaul123/zaplib-ci@sha256:aec4766b988a9b716084ef9faeee9b9c383558ca037c53a1a6c6bf4e34035690
    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v1
      - uses: actions/setup-node@master
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: zaplib/scripts/ci/build_web_ci.sh
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
    timeout-minutes: 20 # should only be triggered if there are unclosed handles in the Jest tests
  browser_tests:
    runs-on: ubuntu-latest
    container:
      image: janpaul123/zaplib-ci@sha256:aec4766b988a9b716084ef9faeee9b9c383558ca037c53a1a6c6bf4e34035690
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Get full repo; necessary for `find_screenshots_compare_commit.sh`
      - uses: Swatinem/rust-cache@v1
      - uses: actions/setup-node@master
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: zaplib/scripts/ci/browser_tests.sh
        env:
          BROWSERSTACK_KEY: ${{ secrets.BROWSERSTACK_KEY }}
      # Download the previous screenshots after running the tests, to give the main branch a bit
      # more time to upload, if it was just merged.
      - run: zaplib/scripts/ci/find_screenshots_compare_commit.sh
      - uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ci.yaml
          commit: ${{ env.SCREENSHOT_COMPARE_COMMIT_HASH }}
          name: screenshots
          path: previous_screenshots/
        continue-on-error: true
      - run: zaplib/scripts/ci/browser_tests_upload_screenshots.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
      - uses: peter-evans/commit-comment@v1
        with:
          body: ${{ env.SCREENSHOT_GITHUB_MESSAGE }}
      - uses: actions/upload-artifact@v2
        with:
          name: screenshots
          path: screenshots_report/screenshots/
  checks_for_all_targets_debug:
    runs-on: ubuntu-latest
    container:
      image: janpaul123/zaplib-ci@sha256:aec4766b988a9b716084ef9faeee9b9c383558ca037c53a1a6c6bf4e34035690
    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v1
      - run: zaplib/scripts/ci/checks_for_all_targets_debug.sh
  checks_for_all_targets_release:
    runs-on: ubuntu-latest
    container:
      image: janpaul123/zaplib-ci@sha256:aec4766b988a9b716084ef9faeee9b9c383558ca037c53a1a6c6bf4e34035690
    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v1
      - run: zaplib/scripts/ci/checks_for_all_targets_release.sh
  debug_builds_native:
    runs-on: ubuntu-latest
    container:
      image: janpaul123/zaplib-ci@sha256:aec4766b988a9b716084ef9faeee9b9c383558ca037c53a1a6c6bf4e34035690
    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v1
      - run: zaplib/scripts/ci/debug_builds_native.sh
  debug_builds_wasm:
    runs-on: ubuntu-latest
    container:
      image: janpaul123/zaplib-ci@sha256:aec4766b988a9b716084ef9faeee9b9c383558ca037c53a1a6c6bf4e34035690
    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v1
      - run: zaplib/scripts/ci/debug_builds_wasm.sh
  release_builds_native:
    runs-on: ubuntu-latest
    container:
      image: janpaul123/zaplib-ci@sha256:aec4766b988a9b716084ef9faeee9b9c383558ca037c53a1a6c6bf4e34035690
    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v1
      - run: zaplib/scripts/ci/release_builds_native.sh
  release_builds_wasm:
    runs-on: ubuntu-latest
    container:
      image: janpaul123/zaplib-ci@sha256:aec4766b988a9b716084ef9faeee9b9c383558ca037c53a1a6c6bf4e34035690
    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v1
      - run: zaplib/scripts/ci/release_builds_wasm.sh
  lint:
    runs-on: ubuntu-latest
    container:
      image: janpaul123/zaplib-ci@sha256:aec4766b988a9b716084ef9faeee9b9c383558ca037c53a1a6c6bf4e34035690
    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v1
      - run: zaplib/scripts/ci/lint.sh
  tests:
    runs-on: ubuntu-latest
    container:
      image: janpaul123/zaplib-ci@sha256:aec4766b988a9b716084ef9faeee9b9c383558ca037c53a1a6c6bf4e34035690
    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v1
      - run: zaplib/scripts/ci/tests.sh
  build_and_push_to_docker_hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: janpaul123
          password: ${{ secrets.DOCKER_PASSWORD }}
      - run: zaplib/scripts/docker_ci_build.sh && zaplib/scripts/docker_ci_push.sh
